image: alpine/helm:3.14.2

pipelines:
  branches:
    main:
      - stage:
          name: Deploy to Chartmuseum
          deployment: production
          steps:
            - step:
                name: Build and deploy helm chart
                script:
                  - apk add curl
                  - bin/deploy-chart-lib
            - step:
                name: Mirror to GitHub
                script:
                  - apk add --update --no-cache openssh
                  # bitbucket options will fetch just the current branch, so it is required to fetch all:
                  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
                  # fetch all branches:
                  - git fetch --all
                  # track all branches but HEAD and the current one, which is already being tracked:
                  - for i in $(git branch -a | grep remotes | grep -v "HEAD" | grep -v "$(git rev-parse --abbrev-ref HEAD)"); do git branch --track ${i#remotes/origin/} $i; done
                  # publish the current working copy to gtithub
                  - git push --mirror $GITHUB_REPO_URL

