{{- define "pl-standard-chart.deployment" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  namespace: {{ .Values.namespace }} 
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}-template
  replicas: {{ default 1 .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-template
    spec:
      minReadySeconds: {{ default 10 .Values.minReadySeconds }}
      revisionHistoryLimit: {{ default 5 .Values.revisionHistoryLimit }}
      restartPolicy: {{ default "Always" .Values.restartPolicy }}
      {{ if .Values.registrySecretName }}
      imagePullSecrets:
        - name: {{ .Values.registrySecretName }}
      {{ end }}

      volumes:
        {{- range $volume := .Values.persistentVolumeClaims }}
        - name: {{ $.Values.appName }}-volume-{{ $volume.name }}
          persistentVolumeClaim:
            claimName: {{ $.Values.appName }}-claim-{{ $volume.name }}
        {{- end }}

      containers:
        - name: {{ .Values.appName }}-container
          image: {{ .Values.imageLocation }}
          imagePullPolicy: {{ default "Always" .Values.imagePullPolicy }}    
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "200m" | quote }}
              memory: {{ .Values.resources.limits.memory | default "256Mi" | quote }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "100m" | quote }}
              memory: {{ .Values.resources.requests.memory | default "128Mi" | quote }}
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: "kubernetes.io/hostname"
              whenUnsatisfiable: "ScheduleAnyway"
              labelSelector:
                matchLabels:
                  app: {{ .Values.appName }}-template
          args:          
            {{- range $arg := .Values.containerArgs }}
            - {{ $arg | quote }}
            {{- end }}
          ports:          
            {{- range $port := .Values.containerPorts }}
            - name: {{ $port.name }}
              containerPort: {{ $port.targetPort }}
              {{ if $port.protocol }}
              protocol: {{ $port.protocol }}
              {{ end }}
            {{- end }}   
          envFrom:
            {{- range $secret := .Values.secrets }}
            - secretRef:
                name: {{ $secret.name }}
            {{- end }}
          env:
            {{- range $key, $val := .Values.envVars }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          volumeMounts:
            {{- range $volume := .Values.persistentVolumeClaims }}
            - mountPath: {{ $volume.mountPath | quote }}
              name: {{ $.Values.appName }}-volume-{{ $volume.name }}
            {{- end }}   

{{- end }}