apiVersion: v2
name: pl-cluster-setup-chart
description: An umbrella chart to deploy and configure base services like cert-manager, external-dns, and ingress-nginx.
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: cert-manager
    version: "v1.14.5"
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled
  - name: external-dns
    version: "1.14.1"
    repository: "https://kubernetes-sigs.github.io/external-dns/"
    condition: external-dns.enabled
  - name: ingress-nginx
    version: "4.10.1"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress-nginx.enabled
