{{- if eq .Values.profile "generic" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuerName }}
    {{- if .Values.ingressAnnotations }}
    {{- range $key, $value := .Values.ingressAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
    {{ if .Values.disableExternalDNS }}
    external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
    external-dns.alpha.kubernetes.io/hostname: ""
    {{ end }}    
    {{ if .Values.disableContentSizeChecksNginx }}
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    {{ end }}    
spec:
  ingressClassName: {{ .Values.ingressClassName | default "nginx" }}
  tls:
  - hosts:
    {{- range $host := .Values.hosts }}
    - {{ $host.domainName }}
    {{- end }}
    secretName: {{ .Values.tlsSecretName }}
  rules:
  {{- range $host := .Values.hosts }}
  - host: {{ $host.domainName }}
    http:
      paths:
        {{- range $path := $host.ingressPaths }}
        - path: {{ $path.path }}
          pathType: {{ $path.type }}
          backend:
            service:
              name: {{ $.Values.appName }}-service
              port:
                number: {{ $path.servicePort }}
        {{- end }}
  {{- end }}
{{- end }}
