namespace: hello-world
appName: hello-world
replicas: 2
imageLocation: hashicorp/http-echo
registrySecretName: polar-labs-registry
containerArgs:
  - -text=echo1
containerPorts:
  - name: web-ui
    port: 80
    targetPort: 5678
envVars:
  TEST: test
secrets:
  - name: do-creds
    type: Opaque
    data:
      TEST: test
clusterIssuerName: letsencrypt-staging
tlsSecretName: hello-world-tls
# disableExternalDNS: true
resources:
  limits:
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"
hosts:
  - domainName: test1111.polarlabs.ca
    ingressPaths:
      - path: /
        type: Prefix
        servicePort: 80
  - domainName: test2222.polarlabs.ca
    ingressPaths:
      - path: /
        type: Prefix
        servicePort: 80
# persistentVolumeClaims:
#   - name: test-pvc
#     storage: 5Gi
#     mountPath: /data