{{- if or (and (eq .Values.profile "gcp") (.Values.gcp.ingress.enabled | default false)) (and (eq .Values.profile "generic") (.Values.ingressClassName | default "" | ne "")) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.appName }}-tls
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.tlsSecretName }}
  issuerRef:
    name: {{ .Values.clusterIssuerName }}
    kind: ClusterIssuer
  dnsNames:
    {{- range .Values.hosts }}
    - {{ .domainName }}
    {{- end }}
{{- end }}
