apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.appName }}-tls
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.tlsSecretName }}
  issuerRef:
    name: {{ .Values.clusterIssuerName }}
    kind: ClusterIssuer
  dnsNames:
    {{- range .Values.hosts }}
    - {{ .domainName }}
    {{- end }}
