{{- range $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $.Values.namespace }}
type: {{ $secret.type }}
stringData: 
  {{- range $key, $val := $secret.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

---
{{- end }}