apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}-template
  ports:
    {{- range $port := .Values.containerPorts }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      {{- if $port.nodePort }}
      nodePort: {{ $port.nodePort }}
      {{- end }}
      {{- end }}
      {{ if $port.protocol }}
      protocol: {{ $port.protocol }}
      {{ end }}
    {{- end }}