apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.namespace }}
  {{- if .Values.gcp.backendConfig.enabled }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Values.gcp.backendConfig.name | default (printf "%s-backendconfig" .Values.appName) }}"}'
    cloud.google.com/neg: '{"ingress": true}'
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.appName }}-template
  ports:
    {{- range $port := .Values.containerPorts }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      {{- if $port.protocol }}
      protocol: {{ $port.protocol }}
      {{- end }}
    {{- end }}