apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName | default .Values.appName }}
  namespace: {{ .Values.namespace }}
  {{- if .Values.serviceAccountName }}
  annotations:
    {{- range $key, $value := .Values.gcp.serviceAccountAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
