{{- range $volume := .Values.persistentVolumeClaims }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.appName }}-claim-{{ $volume.name }}
  namespace: {{ $.Values.namespace }}
spec:
  storageClassName: {{ $volume.storageClassName | default $.Values.storageClassName | default "do-block-storage" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $volume.storage }}
---
{{- end }}