apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Values.appName }}-backendconfig
  namespace: {{ .Values.namespace }}
spec:
  healthCheck:
    checkIntervalSec: {{ .Values.gcp.backendConfig.checkIntervalSec | default 30 }}
    timeoutSec: {{ .Values.gcp.backendConfig.timeoutSec | default 5 }}
    healthyThreshold: {{ .Values.gcp.backendConfig.healthyThreshold | default 1 }}
    unhealthyThreshold: {{ .Values.gcp.backendConfig.unhealthyThreshold | default 5 }}
    port: {{ .Values.gcp.backendConfig.port | default 80 }}
    type: {{ .Values.gcp.backendConfig.type | default "HTTP" }}
    requestPath: {{ .Values.gcp.backendConfig.requestPath | default "/healthz" }}
